### ISSUE TITLE
bilibili@1.1.1: hash check failed

### ISSUE THREAD

**Issue by ohmyarch** [caoli5288/scoop-bucket#1]
App:         caoli5288/bilibili
URL:         https://dl.hdslb.com/mobile/fixed/bili_win/bili_win-install.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    5d5d86963f5a922ce5f616159e0d5705602aa39c7520dc8a5f0f020adb74a3da
Actual:      96718413342daca81b375a80fc996fa1ab19fc199c73bd9002eb32eccdbbb35f

**Comment by caoli5288** [comment]
closed https://github.com/caoli5288/scoop-bucket/commit/cc4364768cd850f9d7be02279d5330e76413f990
